### PR TITLE
Feat/instance metadata options - Updated

### PR DESCRIPTION
**Pull request by rwc**
Full credit goes to @zen and his prior work in https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/88. Simply fixing up the issues @Nuru called out in order to get this over the finish line for production use.

## what
* Adds support for newly introduced instance tags in metadata

## why
* This is very handy for setting up a hostname from "Tag:Name" and other useful automations without AWS SDK installed

## references
* [Tags as Metadata AWS Functionality](https://aws.amazon.com/about-aws/whats-new/2022/01/instance-tags-amazon-ec2-instance-metadata-service/)
* Closes https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/issues/87
* Previously https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/88

### CODE REVIEW

**Review by jamengual — DISMISSED** [review]

**Comment by nitrocode** [comment]
@rwc please run `make init && make pr/auto-format`

**Comment by nitrocode** [comment]
@rwc please also bump the aws provider to 4.x in versions.tf and examples/complete/versions.tf

**Comment by rwc** [comment]
Added @cloudpossebot as a contributor to my repository, but it must accept the invite in order to push its changes if I understand correctly.

**Review by nitrocode — APPROVED** [review]

**Pull request merged**
