### PR TITLE
Feature/additional tag specifications

### PR DESCRIPTION
**Pull request by tthayer**
## what
* Adds additional tag_specification blocks

## why
* Spot requests are not currently getting tagged

## references
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#tag-specifications

### CODE REVIEW

**Review by SweetOps — DISMISSED** [review]
need to update AWS provider pinning here https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/blob/master/versions.tf cos this change requires aws-provider >=3.3.0

**Comment by tthayer** [comment]
It looks like the template module has been deprecated: https://registry.terraform.io/providers/hashicorp/template/latest/docs
I'll look at this later today when I have a few minutes.

**Comment by Nuru** [comment]
@tthayer After #39 merges, please rebase and update this PR.

**Comment by nitrocode** [comment]
This would be better as a dynamic using a list to feed into `resource_type`.

**Review by nitrocode — APPROVED** [review]

**Comment by tthayer** [comment]
Thanks for picking up this PR @nitrocode !

**Comment by nitrocode** [comment]
np! If you noticed, I removed the original default of

```hcl
  tag_specifications_resource_types = ["instance", "volume", "elastic-gpu", "spot-instances-request"]
```

because the `elastic-gpu` failed when I did not use elastic so I figured an input variable that can be modified depending on what you need would be the best of both worlds.

**Review by nitrocode — DISMISSED** [review]

**Review by jamengual — APPROVED** [review]

**Pull request merged**
