### PR TITLE
* add throughput to block_device_mapping

### LINKED ISSUE #96: Missing `throughput` in block_device_mappings.
Found a bug? Maybe our [Slack Community](https://slack.cloudposse.com) can help. 

[Slack Community](https://slack.cloudposse.com)

## Describe the Bug
Missing `throughput` in block_device_mappings. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#throughput

## Steps to Reproduce
2. Run '....'
3. Enter '....'

## Screenshots
If applicable, add screenshots or logs to help explain your problem.

## Environment (please complete the following information):

Anything that will help us triage the bug will help. Here are some ideas:
 - OS: [e.g. Linux, OSX, WSL, etc]
 - Version [e.g. 10.15]

### PR DESCRIPTION
**Pull request by zaksamalik**
## what
* add `throughput` to `block_device_mapping`

## why
* allows `throughput` configuration for block device mappings

## references
* closes #96

### CODE REVIEW

**Comment by y3ti** [comment]
Any plans to merge it?

**Comment by Gowiem** [comment]
@zaksamalik can you pull in the `main` branch and deal with any conflicts + please run the following commands, commit, and push the changes:

```
make init
make github/init
make readme
```

**Comment by zaksamalik** [comment]
> @zaksamalik can you pull in the `main` branch and deal with any conflicts + please run the following commands, commit, and push the changes:
> 
> ```
> make init
> make github/init
> make readme
> ```

@Gowiem PR should be ready to go. Please lmk if I missed anything and I will update, thanks.

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
@zaksamalik this requires another approval from someone internal at Cloud Posse. I've requested that in Slack and we'll get this merged shortly. Thanks for the patience!

**Pull request merged**
