### PR TITLE
Normalize metadata service, revert option to use fixed name

### PR DESCRIPTION
**Pull request by Nuru**
## what
- Provide Cloud Posse standard interface to IMDS configuration
- Remove `var.use_name_prefix` parameter
- Set `lifecycle` to ignore changes to `desired_capacity`
- Update module boilerplate to current 

## why
- IMDS:
  - Replaces #56 to keep interfaces standard across Cloud Posse modules
  - Use secure settings (as defined by Bridgecrew) by default
  - Expose all IMDS configuration options
  - Provide sensible default with option to override and make more (or less) secure
- `var.use_name_prefix`
  - This module has always set `create_before_destroy` on the `autoscaling_group`
  - Terraform does not provide a way to make `create_before_destroy` configurable, so this module only supports it being set
  - You must use `name_prefix` with `create_before_destroy` or else a replacement operation will fail
  - The implementation of `var.use_name_prefix` in #60 left the `name` with a trailing `delimiter` and did not support directly specifying the `name`, making it unlikely to be suitable for the purported use case #28
- It is normal and expected for an external source to change the desired capacity of the autoscaling group and Terraform should not override that. If desired, you can set the size of the group by changing `min_size` and `max_size` to both be the desired size.  #29  #37  #58

### CODE REVIEW

**Review by osterman — APPROVED** [review]

**Comment by nitrocode** [comment]
The problem with using a `name_prefix` on any resource is that it makes it impossible to import existing infrastructure into a terraform module.

Due to that limitation, I'd advocate adding back the `var.use_name_prefix` input so we have the option to use the `name` argument instead of the `name_prefix` argument.

**Comment by Nuru** [comment]
@nitrocode wrote
> The problem with using a `name_prefix` on any resource is that it makes it impossible to import existing infrastructure into a terraform module.
> 

If you imported the existing infrastructure (that did not use name_prefix) into this module, it would break as soon as you changed anything because of the `create_before_destroy` lifecycle rule. To me that is a worse situation than not being able to import the infrastructure in the first place. 

Even worse would be that we now have added a "feature" that we do not actually support, confusing all users of the module. 

If you want to import existing infrastructure that uses name instead of name_prefix, you need to fork this module and take out the lifecycle rule.

**Pull request merged**
