### PR TITLE
fix: block_device_mappings required optional fields

### PR DESCRIPTION
**Pull request by MaxymVlasov**
## what

Fix 0.37.0

```
│ Error: Invalid value for input variable
│ 
│   on main.tf line 125, in module "autoscale_group":
│  125:   block_device_mappings       = var.block_device_mappings
│ 
│ The given value is not suitable for
│ module.autoscale_group.var.block_device_mappings declared at
│ .terraform/modules/autoscale_group/variables.tf:72,1-33: incorrect list
│ element type: attribute "ebs": attribute "throughput" is required.
╵
```

## why

As per the code in main.tf, all these stuff are optional

https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/blob/b757eb9037b9eae3235522800530117e66d535b2/main.tf#L6-L24

## references
https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/97

### CODE REVIEW

**Review by max-lobur — APPROVED** [review]

**Comment by MaxymVlasov** [comment]
Ehh, it can't do back-push fixes, meh

**Comment by max-lobur** [comment]
Merging a few PRs at a time

**Review by max-lobur — APPROVED** [review]

**Pull request merged**
