### PR TITLE
Expose metadata HTTP tokens

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Expose aws_launch_template -> metadata_options -> http_tokens.

### CODE REVIEW

**Review by htplbc — APPROVED** [review]

**Comment by alexjurkiewicz** [comment]
The failing test should be fixed 🙌

**Comment by mihaiplesa** [comment]
Can we get this in?

**Review by nitrocode — APPROVED** [review]

**Review by jamengual — APPROVED** [review]

**Pull request merged**
