### PR TITLE
Fix: instance refresh missing properties

### PR DESCRIPTION
**Pull request by ebarriosjr**
## what
This PR adds two missing properties to the instance_refresh stanza.

## why
Right now there is no way to configure scale_in_protected_instances and standby_instances in the instance refresh stanza.

## references
This solves: #120

### CODE REVIEW

**Comment by RoseSecurity** [comment]
@dotCipher, I am currently utilizing `v0.34.1` of this module with no values set for `instance_refresh` and woke up to this error:

```console
Error: starting Auto Scaling Group instance refresh: 
ValidationError: 2 validation errors detected: Value '' at 'preferences.scaleInProtectedInstances' failed to satisfy constraint: 
Member must satisfy enum value set: [Ignore, Wait, Refresh]; 
Value '' at 'preferences.standbyInstances' failed to satisfy constraint: Member must satisfy enum value set: 
[Terminate, Ignore, Wait]
```

Do you think this PR would fix the issue?

**Comment by ebarriosjr** [comment]
@RoseSecurity  I had the same issue. If you upgrade to v0.35.1 this should solve the issue you are having. But if you try to change any of the values from those properties it is not going to work. Their are set to the default that is "Ignore". This PR should fix that and allow you to change the values.

**Comment by ebarriosjr** [comment]
@RoseSecurity I missed adding the values to the variables file but it is fixed now. I tested it by setting my fork as the source of the module and it works. Just FYI

**Review by dudymas — APPROVED** [review]

**Comment by dudymas** [comment]
Thanks for the contribution!

**Comment by y3ti** [comment]
This change is not compatible with [aws provider 4.x](https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/blob/main/versions.tf#L7) (it requires at least aws provider `5.16`):

https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#5160-september--8-2023

**Pull request merged**
