### PR TITLE
Add support for Mixed Instance Spot Policy Autoscaling.

### PR DESCRIPTION
**Pull request by ChrisMcKee**
Does as the label says; adds an example using it which I used to test that it works as expected.

The "make && make init" keeps trying to install and setup terraform 0.11 which is mildly infuriating. 

Hacked around it; added a git attributes file as well as I doubt you want my windows crlfs in there 😉

### CODE REVIEW

**Comment by ChrisMcKee** [comment]
@osterman could you have a poke 😉

**Comment by ChrisMcKee** [comment]
I'd also pull out the type as per https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/issues/18 but that can be a separate pr if needed

**Comment by ChrisMcKee** [comment]
If this is unwanted let me know and I'll close it 🤷‍♂

**Comment by maximmi** [comment]
@ChrisMcKee thank you for your contribution
could you please address some fixes:
* remove `.editorconfig` file
* remove update files with `linux` EOL if needed and remove `.gitattributes` file

**Comment by ChrisMcKee** [comment]
@maximmi as https://github.com/cloudposse/terraform-aws-ec2-autoscale-group/pull/19 came after this PR and has been merged it appears to be trying to achieve the same thing?
You should have gitattributes files; I may not be the right person to be adding them but in general unless you want mixed line endings between platforms.

**Pull request closed without merging**
